"""add_total_upvotes_to_activity

Revision ID: 24bf56c84187
Revises: a9c1f2d3e4b5
Create Date: 2026-01-19 22:42:21.461937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24bf56c84187'
down_revision: Union[str, None] = 'a9c1f2d3e4b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity', sa.Column('total_upvotes', sa.Integer(), nullable=True))
    op.execute("UPDATE activity SET total_upvotes = 0")
    op.alter_column('activity', 'total_upvotes', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activity', 'total_upvotes')
    # ### end Alembic commands ###
