"""add_avatar_url_to_event

Revision ID: 37755f5fd702
Revises: 40a1b2c3d4e5
Create Date: 2025-12-15 00:44:33.557771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37755f5fd702'
down_revision: Union[str, None] = '40a1b2c3d4e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('avatar_url', sa.String(), nullable=True))
    op.drop_index('ix_event_invite_code', table_name='event')
    op.drop_column('event', 'invite_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('invite_code', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index('ix_event_invite_code', 'event', ['invite_code'], unique=True)
    op.drop_column('event', 'avatar_url')
    # ### end Alembic commands ###
