"""Add intensity fields to Activity

Revision ID: 4e2e81349cee
Revises: bb8375fd933a
Create Date: 2025-12-08 19:00:29.177779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e2e81349cee'
down_revision: Union[str, None] = 'bb8375fd933a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity', sa.Column('physical_intensity', sa.Integer(), nullable=True))
    op.add_column('activity', sa.Column('mental_challenge', sa.Integer(), nullable=True))
    op.add_column('activity', sa.Column('social_interaction_level', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activity', 'social_interaction_level')
    op.drop_column('activity', 'mental_challenge')
    op.drop_column('activity', 'physical_intensity')
    # ### end Alembic commands ###
