"""Initial migration

Revision ID: bb8375fd933a
Revises: 
Create Date: 2025-12-08 18:28:14.238559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bb8375fd933a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('category', sa.Enum('action', 'food', 'relax', 'party', 'culture', 'outdoor', 'creative', name='eventcategory'), nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('location_region', sa.Enum('OOE', 'TIR', 'SBG', 'STMK', 'KTN', 'VBG', 'NOE', 'WIE', 'BGL', name='region'), nullable=False),
    sa.Column('location_city', sa.String(), nullable=True),
    sa.Column('location_address', sa.String(), nullable=True),
    sa.Column('coordinates', sa.JSON(), nullable=True),
    sa.Column('est_price_per_person', sa.Float(), nullable=True),
    sa.Column('price_includes', sa.Text(), nullable=True),
    sa.Column('price_comment', sa.Text(), nullable=True),
    sa.Column('short_description', sa.String(), nullable=False),
    sa.Column('long_description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('gallery_urls', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('season', sa.Enum('all_year', 'spring', 'summer', 'autumn', 'winter', name='season'), nullable=True),
    sa.Column('risk_level', sa.Enum('low', 'medium', 'high', name='risklevel'), nullable=True),
    sa.Column('duration', sa.String(), nullable=True),
    sa.Column('typical_duration_hours', sa.Float(), nullable=True),
    sa.Column('group_size_min', sa.Integer(), nullable=True),
    sa.Column('group_size_max', sa.Integer(), nullable=True),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('contact_email', sa.String(), nullable=True),
    sa.Column('contact_phone', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('birthday', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('room',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_favorites',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('activity_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'activity_id')
    )
    op.create_table('event',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('room_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('phase', sa.Enum('proposal', 'voting', 'scheduling', 'info', name='eventphase'), nullable=True),
    sa.Column('time_window', sa.JSON(), nullable=True),
    sa.Column('voting_deadline', sa.DateTime(), nullable=True),
    sa.Column('budget_type', sa.Enum('total', 'per_person', name='budgettype'), nullable=True),
    sa.Column('budget_amount', sa.Float(), nullable=True),
    sa.Column('participant_count_estimate', sa.Integer(), nullable=True),
    sa.Column('location_region', sa.Enum('OOE', 'TIR', 'SBG', 'STMK', 'KTN', 'VBG', 'NOE', 'WIE', 'BGL', name='region'), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('proposed_activity_ids', postgresql.ARRAY(sa.UUID()), nullable=True),
    sa.Column('chosen_activity_id', sa.UUID(), nullable=True),
    sa.Column('final_date_option_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['chosen_activity_id'], ['activity.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('room_member',
    sa.Column('room_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('owner', 'admin', 'member', name='roomrole'), nullable=True),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('room_id', 'user_id')
    )
    op.create_table('date_option',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('start_time', sa.String(), nullable=True),
    sa.Column('end_time', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event_participant',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('is_organizer', sa.Boolean(), nullable=True),
    sa.Column('has_voted', sa.Boolean(), nullable=True),
    sa.Column('date_response', sa.Enum('yes', 'no', 'maybe', name='dateresponsetype'), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('event_id', 'user_id')
    )
    op.create_table('vote',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('activity_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('vote', sa.Enum('for_', 'against', 'abstain', name='votetype'), nullable=False),
    sa.Column('voted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('event_id', 'activity_id', 'user_id')
    )
    op.create_table('date_response',
    sa.Column('date_option_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('response', sa.Enum('yes', 'no', 'maybe', name='dateresponsetype'), nullable=False),
    sa.Column('contribution', sa.Float(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['date_option_id'], ['date_option.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('date_option_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('date_response')
    op.drop_table('vote')
    op.drop_table('event_participant')
    op.drop_table('date_option')
    op.drop_table('room_member')
    op.drop_table('event')
    op.drop_table('user_favorites')
    op.drop_table('room')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('activity')
    # ### end Alembic commands ###
